### ISSUE TITLE
License addition request

### ISSUE THREAD

**Issue by jasonmhead** [fredconex/PixelLlama#3]
Thanks for sharing!

Could this get a MIT or Apache2 license?

**Comment by fredconex** [comment]
Hey, you're welcome!

I'm not familiar with licensing, mostly all my previous work was closed so I never had to worry about it at all. I will give it a look but what is the idea behind the licensing?

**Comment by fredconex** [comment]
Hey, 

I've just created the MIT license, so you guys are free to do whatever you like with it.

**Comment by jasonmhead** [comment]
Thanks!

Open source licensing can give people the comfort to adopt and adapt shared code, and perhaps contribute back.
Making it more likely that people will do interesting and useful things with shared code.
